# Site
name: 'The Ultimate Language Combat'
description: 'The ULC is a blog page to determine which language is better for what'
logo: 'assets/images/home_v1_small.png'
favicon: 'assets/images/favicon.ico'
baseurl: 'https://random-6.github.io/ultimate_language_combat/'
#baseurl: ''
disqus: 'demowebsite'
email: 'wowthemesnet@gmail.com'
mailchimp-list: 'https://wowthemes.us11.list-manage.com/subscribe/post?u=8aeb20a530e124561927d3bd8&amp;id=8c3d2d214b'

include: ["_pages"]
permalink: /:title/

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-seo-tag

authors:
    xisca:
      name:           Xisca
      site:           https://xiscasite.com
      avatar:         assets/images/xisca_1.jpeg
      avatar_large:   assets/images/xisca_2.jpeg
      bio:            "Hi, I'm Xis. Data Scientist | Music composer | Book & Cats Lover!"
      email:          mfpericas@gmail.com
      twitter:        https://twitter.com/wowthemesnet

    alex:
      name:           Alex
      site:           https://alexsite.com
      avatar:         assets/images/alex_1.jpeg
      avatar_large:   assets/images/alex_2.jpeg
      bio:            "Hi, I'm Alex. Data Scientist | PhD | Philosophy & Art Enthusiast"
      email:          alexandraabos@gmail.com
      twitter:        https://twitter.com/alexx_abos

# Defaults
defaults:

  # all posts
  - scope:
      path: "_posts"
    values:
      layout: post
      author: xisca
      avatar: /assets/images/xisca_1.jpg

  # all pages
  - scope:
      path: "_pages"
    values:
      layout: page

# Syntax
markdown: kramdown
highlighter: rouge

# Paginate
paginate: 10


# Exclude metadata and development time dependencies (like Grunt plugins)
exclude: [README.markdown, package.json, grunt.js, Gruntfile.js, Gruntfile.coffee, node_modules]
